# Generated by Django 2.2.5 on 2019-10-17 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_content', models.TextField()),
                ('question_category', models.IntegerField()),
                ('question_type', models.IntegerField()),
                ('question_sound_file', models.FilePathField(path='/quesion_sound/')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=100)),
                ('test_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('resume_id', models.AutoField(primary_key=True, serialize=False)),
                ('resume_name', models.CharField(max_length=100)),
                ('resume_dob', models.DateTimeField()),
                ('resume_mobile', models.TextField()),
                ('resume_email', models.EmailField(max_length=254)),
                ('resume_additional_information', models.TextField()),
                ('resume_link', models.TextField()),
                ('resume_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTest',
            fields=[
                ('qt_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_index', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Test')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnwser',
            fields=[
                ('qa_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('interview_id', models.AutoField(primary_key=True, serialize=False)),
                ('interview_link', models.TextField()),
                ('interview_result', models.TextField()),
                ('interview_videorecord_file', models.FilePathField(path='/interview_video/')),
                ('interview_conversation_text', models.TextField()),
                ('interview_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('interview_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Test')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Resume')),
            ],
        ),
    ]
