# Generated by Django 2.2.5 on 2019-10-10 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_content', models.TextField()),
                ('question_category', models.IntegerField()),
                ('question_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=100)),
                ('test_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.User')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('resume_id', models.AutoField(primary_key=True, serialize=False)),
                ('resume_name', models.TextField()),
                ('resume_dob', models.DateTimeField()),
                ('resume_mobile', models.TextField()),
                ('resume_email', models.EmailField(max_length=254)),
                ('resume_additional_information', models.TextField()),
                ('resume_link', models.TextField()),
                ('resume_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.User')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTest',
            fields=[
                ('qt_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Test')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnwser',
            fields=[
                ('qa_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('interview_id', models.AutoField(primary_key=True, serialize=False)),
                ('interview_link', models.TextField()),
                ('interview_result', models.TextField()),
                ('interview_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.User')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Resume')),
            ],
        ),
    ]
